baseURL = 'https://bred1810.github.io/christmas-projects'
title = 'Christmas Projects'
theme = "hugo-book"

[markup]
[markup.goldmark.renderer]
    unsafe = true

[menu]
[[menu.after]]
    name = "Browse Code"
    url = "https://github.com/CoderDojoBrighton/christmas-projects"
    weight = 10

# See details at https://github.com/alex-shpak/hugo-book
[params]
    BookTheme = 'light'
    BookToC = true
    BookSearch = false
    BookComments = false
    BookLogo = "favicon.png"
    BookSection = 'docs'
